export const BannerHome = {
  en: {
    MEDICAL_FOUNDATION: "MEDICAL FOUNDATION",
    COMPREHENSIVE_HEALTH_CARE: "COMPREHENSIVE HEALTH CARE",
    FindAReasonToTest: "Find a reason to test",
    Examination: "Examination",
    Specialist: "specialist",
    fromFarAway: "from far away",
    generality: "generality",
    Test: "Test",
    medicine: "medicine",
    Health: "Health",
    spirit: "spirit",
    dentistry: "dentistry",
  },
  vn: {
    MEDICAL_FOUNDATION: "NỀN TẢNG Y TẾ",
    COMPREHENSIVE_HEALTH_CARE: "CHĂM SÓC SỨC KHỎE TOÀN DIỆN",
    FindAReasonToTest: "Tìm lý do khám",
    Examination: "Khám",
    Specialist: "chuyên Khoa",
    fromFarAway: "từ xa",
    generality: "tổng quát",
    Test: "Xét nghiệm",
    medicine: "y học",
    Health: "Sức khỏe",
    spirit: "tinh thần",
    dentistry: "nha khoa",
  },
};
