export const UserRedux = {
  en: {
    UsersSystem: "Users System",
    Clinics: "Clinics",
    Specialties: "Specialties",
    Handbook: "Handbook",
    Welcome: "Welcome",
    Password: "Password",
    FirstName: "FirstName",
    LastName: "LastName",
    Address: "Address",
    Gender: "Gender",
    Role: "Role",
    Position: "Position",
    PhoneNumber: "PhoneNumber",
    Image: "Image",
    AddNewUser: "Add New User",
    Option: "Option",
    CreateNewUser: "Create New User",
    UpdateUser: "Update User",
    DeleteUser: "Delete User",
    Create: "Create",
    Update: "Update",
    Delete: "Delete",
    Close: "Close",
  },
  vn: {
    UsersSystem: "Hệ Thống",
    Clinics: "Phòng Khám",
    Specialties: "Chuyên Khoa",
    Handbook: "Cẩm Nang",
    Welcome: "Xin Chào",
    Password: "Mật Khẩu",
    FirstName: "Họ",
    LastName: "Tên",
    Address: "Địa Chỉ",
    Gender: "Giới Tính",
    Role: "Quyền",
    Position: "Chức Danh",
    PhoneNumber: "Số Điện Thoại",
    Image: "Hình Ảnh",
    AddNewUser: "Thêm Mới Người Dùng",
    Option: "Lựa Chọn",
    CreateNewUser: "Thêm Người Dùng",
    UpdateUser: "Cập Nhật Người Dùng",
    DeleteUser: "Xóa Người Dùng",
    Create: "Thêm",
    Update: "Sửa",
    Delete: "Xóa",
    Close: "Hủy",
  },
};
